version: '3.8'

services:
  sds-node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SDS_VERSION=${SDS_VERSION:-main}
        - UID=${UID:-2048}
        - GID=${GID:-2048}
    image: sds
    container_name: sds-node
    ports:
      - "${NETWORK_PORT:-18081}:${NETWORK_PORT:-18081}"
    environment:
      - NETWORK_ADDRESS=${NETWORK_ADDRESS}
      - MNEMONIC_PHRASE=${MNEMONIC_PHRASE}
      - NETWORK_PORT=${NETWORK_PORT:-18081}
    volumes:
      - ./sds-data:/sds
    env_file:
      - .env

